In [19]:
import os
import sys
from annoy import AnnoyIndex
import pandas as pd
import numpy as np

In [20]:
debug=False
doTest=False
nrEventToDo=1
nrBucketToDo=2
bucketSize=20

In [21]:
#inputFolderName="/Users/luizaadelinaciucu/Work/ATLAS/TrackML/input/ttbar_mu200-generic"
inputFolderName="/Users/luizaadelinaciucu/Work/ATLAS/data/TrackML/ttbar_mu200-generic"
outputFolderName="/Users/luizaadelinaciucu/Work/ATLAS/TrackML/output2"

In [22]:
def get_eventNumber_from_fileName(fileName):
    eventNumber=fileName.replace("event","").replace("-hits.csv","")
    return eventNumber

In [23]:
list_eventNumber=[]
for fileName in sorted(os.listdir(inputFolderName)):
    if fileName.endswith("hits.csv"):
        print(fileName)
        eventNumber=get_eventNumber_from_fileName(fileName)
        print(eventNumber)
        list_eventNumber.append(eventNumber)
print("list_eventNumber",list_eventNumber)
        


event000000000-hits.csv
000000000
event000000001-hits.csv
000000001
event000000002-hits.csv
000000002
event000000003-hits.csv
000000003
event000000004-hits.csv
000000004
event000000005-hits.csv
000000005
event000000006-hits.csv
000000006
event000000007-hits.csv
000000007
event000000008-hits.csv
000000008
event000000009-hits.csv
000000009
event000000010-hits.csv
000000010
event000000011-hits.csv
000000011
event000000012-hits.csv
000000012
event000000013-hits.csv
000000013
event000000014-hits.csv
000000014
event000000015-hits.csv
000000015
event000000016-hits.csv
000000016
event000000017-hits.csv
000000017
event000000018-hits.csv
000000018
event000000019-hits.csv
000000019
event000000020-hits.csv
000000020
event000000021-hits.csv
000000021
event000000022-hits.csv
000000022
event000000023-hits.csv
000000023
event000000024-hits.csv
000000024
event000000025-hits.csv
000000025
event000000026-hits.csv
000000026
event000000027-hits.csv
000000027
event000000028-hits.csv
000000028
event000000029

In [6]:
def buildAnnoyIndex(nparray_position,metric="angular",ntrees=10,debug=False): 
    numberDimension=nparray_position.shape[1] # 3 (x,y,z)
    if debug:
        print("numberDimension",numberDimension)
    index=AnnoyIndex(numberDimension,metric)
    if debug:
        print("type(index)",type(index))
        print("enumerate data")
    # add each hit to the index
    for i,position in enumerate(nparray_position):
        if debug:
            print("i",i,"position",position)
        index.add_item(i,position)
    # done for loop over hits
    # build the index with 10 trees
    index.build(ntrees) # 10 trees
    return index
# done function

In [7]:
def get_input_output_from_df_hits(df_hits,index):
    list_nparray_input=[]
    list_nparray_output=[]
    
    nparray_volume_id=df_hits["volume_id"].values
    nparray_layer_id=df_hits["layer_id"].values
    counter=0
    
    for i in range(len(df_hits)):
        if doTest==True and counter>(nrBucketToDo-1):
            continue
        if (nparray_volume_id[i]==8 and nparray_layer_id[i]==2)==False:
            continue
        counter+=1
        if debug==True:
            print(i)
            
        # using annoy to find the 20 nearest neighboring hits by angle to this hit
        list_index=index.get_nns_by_item(i,bucketSize)
        if debug:
            print("list_index",list_index)
            
        # create bucket
        df_bucket=df_hits.iloc[list_index]
        
        # create NN input for this one bucket
        nparray_input=df_bucket[["x","y","z"]].values.flatten()
        if debug:
            print("nparray_input",nparray_input,"shape",nparray_input.shape,"type",type(nparray_input))
            
        # create NN output for this one bucket
        # identify particle with the largest number of hits in this bucket
        nparray_particle_id=df_bucket["particle_id"].values
        if debug:
            print("nparray_particle_id",nparray_particle_id,"shape",nparray_particle_id.shape,"type",type(nparray_particle_id))
        dict_particle_id_counter={}
        for particle_id in nparray_particle_id:
            if particle_id not in dict_particle_id_counter:
                dict_particle_id_counter[particle_id]=1
            else:
                dict_particle_id_counter[particle_id]+=1
        if debug:
            print("dict_particle_id_counter",dict_particle_id_counter)
            
        # find the maximum value of the counters
        particle_id_with_max_hits=0
        counter_max=0
        for particle_id in dict_particle_id_counter:
            counter=dict_particle_id_counter[particle_id]
            if counter>counter_max:
                counter_max=counter
                particle_id_with_max_hits=particle_id
        if debug:
            print("particle_id_with_max_hits",particle_id_with_max_hits)
            
        # create nparray_output
        list_output=[]
        for particle_id in nparray_particle_id:
            if particle_id==particle_id_with_max_hits:
                list_output.append(1)
            else:
                list_output.append(-1)
        if debug:        
            print("list_output",list_output)
        nparray_output=np.array(list_output)
        if debug:
            print("nparray_output",nparray_output)
            
        if debug and doTest:
            plt.plot(df_bucket.x,df_bucket.y,"o",color="red")
            plt.plot(0,0,"r+")
            plt.title(str(i))
            plt.show()
            # plt.savefig(outputFolderName+"/bucket_"+str(i)+"_"+eventNumber+".pdf")
            
        list_nparray_input.append(nparray_input)
        list_nparray_output.append(nparray_output)
    # done for loop
    
    nparray_input_all=np.array(list_nparray_input)
    nparray_output_all=np.array(list_nparray_output)
    
    return nparray_input_all, nparray_output_all
# done function      

In [8]:
for i,eventNumber in enumerate(list_eventNumber):
    
    if doTest and i>=nrEventToDo:
        continue
        
    print(" ")
    print("**** start i",i,"eventNumber",eventNumber,"*****")
    
    inputFileName_hits_recon=inputFolderName+"/event"+eventNumber+"-hits.csv"
    inputFileName_hits_truth=inputFolderName+"/event"+eventNumber+"-truth.csv"

    fileNameNNInput=outputFolderName+"/NN_1_data_Input_"+eventNumber+".npy"
    fileNameNNOutput=outputFolderName+"/NN_1_data_Output_"+eventNumber+".npy"

    fileNameNNInputTrain=outputFolderName+"/NN_2_data_Input_Train_"+eventNumber+".npy"
    fileNameNNOutputTrain=outputFolderName+"/NN_2_data_Output_Train_"+eventNumber+".npy"

    fileNameNNInputTest=outputFolderName+"/NN_2_data_Input_Test_"+eventNumber+".npy"
    fileNameNNOutputTest=outputFolderName+"/NN_2_data_Output_Test_"+eventNumber+".npy"
    
    df_hits_recon=pd.read_csv(inputFileName_hits_recon)
    df_hits_truth=pd.read_csv(inputFileName_hits_truth)
    df_hits=pd.concat([df_hits_recon,df_hits_truth],axis=1,sort=False)
    # print(df_hits.head())
    
    nparray_position=df_hits[["x","y","z"]].values
    print("nparray_position",nparray_position)
    index=buildAnnoyIndex(nparray_position,metric="angular",ntrees=10,debug=False)
    
    nparray_input_all,nparray_output_all=get_input_output_from_df_hits(df_hits,index)
    print("nparray_input_all",nparray_input_all,"shape",nparray_input_all.shape,"type",type(nparray_input_all))
    print("nparray_output_all",nparray_output_all,"shape",nparray_output_all.shape,"type",type(nparray_output_all))
    
    # we will want later to split in half for train and test
    # so keep only an even number
    # if an odd number of buckets, remove the last one
    nrBuckets=nparray_input_all.shape[0]
    if nrBuckets%2==1:
        # odd number of buckets
        # rewrite the input as to remove the last element
        nparray_input_all=nparray_input_all[0:-1]
        # rewrite the output as to remove the last element
        nparray_output_all=nparray_output_all[0:-1]
    else:
        # if even, do nothing
        pass
    # done if
    print("nparray_input_all",nparray_input_all,"shape",nparray_input_all.shape,"type",type(nparray_input_all))
    print("nparray_output_all",nparray_output_all,"shape",nparray_output_all.shape,"type",type(nparray_output_all))
    
    # reshape for the input to have an extra dimension of size one, needed by Keras
    nparray_input_all=nparray_input_all.reshape(nparray_input_all.shape[0],nparray_input_all.shape[1],1)
    print("nparray_input_all",nparray_input_all,"shape",nparray_input_all.shape,"type",type(nparray_input_all))
    
    # save them to files
    np.save(fileNameNNInput,nparray_input_all)
    np.save(fileNameNNOutput,nparray_output_all)
    
    # split each of input and output by half in train and test
    nrBucket=nparray_input_all.shape[0] # is now an even number
    # create list of even indices to be used for train
    list_index_Train=[i for i in range(nrBucket) if i%2==0]
    # create list of odd indices to be used for train
    list_index_Test=[i for i in range(nrBucket) if i%2==1]

    # split input in Train and Test by giving as index a list of indices
    nparray_Input_Train=nparray_input_all[list_index_Train]
    nparray_Input_Test=nparray_input_all[list_index_Test]
    nparray_Output_Train=nparray_output_all[list_index_Train]
    nparray_Output_Test=nparray_output_all[list_index_Test]

    # save them to files
    np.save(fileNameNNInputTrain,nparray_Input_Train)
    np.save(fileNameNNInputTest,nparray_Input_Test)
    np.save(fileNameNNOutputTrain,nparray_Output_Train)
    np.save(fileNameNNOutputTest,nparray_Output_Test)
# done for loop 

 
**** start i 0 eventNumber 000000000 *****
nparray_position [[ 4.26321e+01  1.62488e+00 -1.50250e+03]
 [ 4.72534e+01  3.84431e+00 -1.50250e+03]
 [ 8.20138e+01  9.53913e+00 -1.50250e+03]
 ...
 [-8.47474e+02  1.96053e+02  2.95550e+03]
 [-8.99313e+02  4.55782e+01  2.95250e+03]
 [-9.69219e+02  9.38630e+01  2.95250e+03]]
nparray_input_all [[  -32.3306     -4.28872  -462.092   ...   -89.3       -15.1782
  -1302.5    ]
 [  -30.0484    -10.8162   -427.981   ...   -47.7968    -14.5214
   -702.     ]
 [  -30.4775     -9.58902  -421.256   ...  -112.212     -40.1146
  -1498.     ]
 ...
 [  -31.3479      2.50689   469.019   ...   -52.6152      1.65826
    817.5    ]
 [  -29.3948     12.5632    406.38    ...   -90.373      34.3218
   1298.     ]
 [  -30.8299     11.6898    435.472   ...   -74.9913     32.0636
   1098.     ]] shape (11993, 60) type <class 'numpy.ndarray'>
nparray_output_all [[-1  1 -1 ... -1 -1 -1]
 [ 1 -1 -1 ... -1 -1 -1]
 [-1 -1 -1 ... -1 -1 -1]
 ...
 [-1 -1 -1 ...  1  1  1]
 [ 1

nparray_position [[ 1.02126e+02  2.04404e+00 -1.50250e+03]
 [ 3.41398e+01  5.55290e-01 -1.50250e+03]
 [ 4.44923e+01  5.23195e+00 -1.50250e+03]
 ...
 [-1.00504e+03  2.13293e+01  2.95250e+03]
 [-9.26789e+02  1.05742e+02  2.95250e+03]
 [-8.70917e+02  2.53786e-02  2.95250e+03]]
nparray_input_all [[-3.34237e+01 -1.16228e+00 -4.85865e+02 ... -4.73806e+01 -7.94887e-01
  -7.02500e+02]
 [-3.17646e+01 -5.90755e+00 -4.87369e+02 ... -5.95524e+01 -1.10314e+01
  -9.62500e+02]
 [-3.35555e+01 -7.85547e-01 -4.77808e+02 ... -4.06138e+01 -6.90610e-01
  -5.97500e+02]
 ...
 [-3.15819e+01 -1.64052e+00  4.85879e+02 ... -3.83472e+01 -5.68068e-01
   5.97500e+02]
 [-3.07577e+01  1.29706e+01  4.69442e+02 ... -9.83814e+01  3.84932e+01
   1.49800e+03]
 [-3.14058e+01  1.48017e+00  4.31334e+02 ... -6.02551e+01 -4.75853e-02
   8.17500e+02]] shape (12928, 60) type <class 'numpy.ndarray'>
nparray_output_all [[ 1  1  1 ... -1  1 -1]
 [ 1  1  1 ... -1  1  1]
 [ 1  1 -1 ... -1 -1 -1]
 ...
 [-1  1  1 ...  1  1 -1]
 [-1 -1 

nparray_input_all [[ -32.7351    -3.13191 -442.867   ...  -44.4534    -1.76822 -602.5    ]
 [ -37.2866   -12.1141  -598.      ...  -44.0492   -13.5834  -698.     ]
 [ -30.5373    -9.41792 -480.159   ...  -42.913    -13.9791  -698.     ]
 ...
 [ -28.7558    12.7489   453.941   ...  -36.3047    14.632    598.     ]
 [ -30.7156    13.7165   473.768   ... -103.475     43.5296  1498.     ]
 [ -31.1939     5.23709  439.216   ...  -63.6257     8.74397  957.5    ]] shape (10917, 60) type <class 'numpy.ndarray'>
nparray_output_all [[-1 -1 -1 ... -1 -1 -1]
 [-1 -1 -1 ...  1  1  1]
 [ 1  1  1 ... -1 -1 -1]
 ...
 [ 1  1  1 ... -1 -1 -1]
 [-1  1  1 ... -1 -1 -1]
 [-1  1  1 ... -1 -1 -1]] shape (10917, 20) type <class 'numpy.ndarray'>
nparray_input_all [[ -32.7351    -3.13191 -442.867   ...  -44.4534    -1.76822 -602.5    ]
 [ -37.2866   -12.1141  -598.      ...  -44.0492   -13.5834  -698.     ]
 [ -30.5373    -9.41792 -480.159   ...  -42.913    -13.9791  -698.     ]
 ...
 [ -29.7822    10.6189   45

nparray_position [[   34.0879      5.51651 -1502.5    ]
 [   30.4625      4.98041 -1502.5    ]
 [   42.4802      4.27113 -1502.5    ]
 ...
 [ -952.578     200.1      2955.5    ]
 [ -871.166      -3.92681  2952.5    ]
 [ -922.792       3.64978  2952.5    ]]
nparray_input_all [[-3.34243e+01 -1.16080e+00 -4.22990e+02 ... -1.13684e+02  5.25224e-01
  -1.50200e+03]
 [-1.09252e+02 -2.06670e+01 -1.49800e+03 ... -4.48832e+01 -6.71720e+00
  -6.02500e+02]
 [-1.13401e+02 -1.03733e+01 -1.50200e+03 ... -4.48832e+01 -6.71720e+00
  -6.02500e+02]
 ...
 [-3.14803e+01  1.60623e-01  4.74692e+02 ... -8.57190e+01 -2.60847e+00
   1.30250e+03]
 [-3.06876e+01  1.42129e+01  4.44426e+02 ... -5.06234e+01  2.07795e+01
   6.98000e+02]
 [-3.15422e+01 -9.37631e-01  4.20860e+02 ... -5.82680e+01 -4.41025e+00
   8.22500e+02]] shape (9182, 60) type <class 'numpy.ndarray'>
nparray_output_all [[-1 -1 -1 ... -1 -1 -1]
 [ 1  1  1 ... -1 -1 -1]
 [ 1  1  1 ... -1 -1 -1]
 ...
 [-1  1  1 ... -1 -1 -1]
 [-1 -1 -1 ... -1 -1 -1]
 [

nparray_position [[   56.2377     10.8709  -1502.5    ]
 [   87.8783     10.3016  -1502.5    ]
 [   75.2433     13.119   -1502.5    ]
 ...
 [ -936.239     174.749    2955.5    ]
 [ -902.414      -3.71995  2952.5    ]
 [ -930.368      48.8547   2952.5    ]]
nparray_input_all [[  -30.1474    -10.533    -429.498   ...   -53.1628    -14.7958
   -702.     ]
 [  -31.8136     -5.76748  -466.794   ...   -68.8521    -11.1615
   -962.5    ]
 [  -31.6424     -6.25717  -458.624   ...   -78.6162    -12.7293
  -1098.     ]
 ...
 [  -29.6303     10.9342    439.372   ...   -48.9162     17.8885
    702.     ]
 [  -30.8918     10.5933    452.372   ...   -29.9776     10.2135
    463.626  ]
 [  -30.6792     14.3615    458.277   ...   -30.7906     12.3865
    425.078  ]] shape (9000, 60) type <class 'numpy.ndarray'>
nparray_output_all [[ 1  1  1 ... -1 -1 -1]
 [-1 -1 -1 ...  1  1  1]
 [-1 -1 -1 ...  1  1  1]
 ...
 [-1  1 -1 ... -1 -1 -1]
 [-1 -1 -1 ... -1 -1 -1]
 [ 1  1  1 ... -1 -1 -1]] shape (9000, 20) t

nparray_position [[ 4.19615e+01  2.97643e+00 -1.50250e+03]
 [ 5.48390e+01  6.39734e+00 -1.50250e+03]
 [ 3.11336e+01  1.47225e+00 -1.50250e+03]
 ...
 [-9.83976e+02  2.49336e+01  2.95250e+03]
 [-8.99335e+02  4.52190e+01  2.95250e+03]
 [-9.95124e+02  1.33707e+01  2.95250e+03]]
nparray_input_all [[-3.41573e+01  9.35866e-01 -4.27085e+02 ... -8.29504e+01  3.84397e-01
  -1.09750e+03]
 [-3.07085e+01 -8.92824e+00 -4.72171e+02 ... -6.00204e+01 -1.74177e+01
  -9.58000e+02]
 [-2.96200e+01 -1.20415e+01 -4.22226e+02 ... -8.41263e+01 -3.59557e+01
  -1.30200e+03]
 ...
 [-3.11432e+01  6.13670e+00  4.76402e+02 ... -5.32467e+01  1.22906e+01
   8.17500e+02]
 [-3.11397e+01  6.19833e+00  4.72302e+02 ... -5.35396e+01  1.23652e+01
   8.22000e+02]
 [-3.09400e+01  9.73867e+00  4.42991e+02 ... -4.75848e+01  1.42779e+01
   7.02000e+02]] shape (9246, 60) type <class 'numpy.ndarray'>
nparray_output_all [[-1 -1 -1 ... -1  1 -1]
 [ 1 -1  1 ... -1 -1  1]
 [ 1  1  1 ... -1 -1 -1]
 ...
 [-1  1  1 ... -1 -1 -1]
 [ 1  1 -

nparray_input_all [[-2.94873e+01 -1.24209e+01 -4.88990e+02 ... -7.38467e+01 -3.44037e+01
  -1.30200e+03]
 [-2.88767e+01 -1.41673e+01 -4.40389e+02 ... -8.25343e+01 -4.19861e+01
  -1.29750e+03]
 [-3.36558e+01 -4.98547e-01 -4.85204e+02 ... -1.06237e+02 -6.98887e+00
  -1.50200e+03]
 ...
 [-7.50376e+01 -4.97773e+00  1.10250e+03 ... -6.17960e+01 -9.05136e+00
   9.62500e+02]
 [-3.13057e+01  3.25570e+00  4.43269e+02 ... -4.32927e+01  6.61424e+00
   6.02000e+02]
 [-3.13456e+01  2.54773e+00  4.90166e+02 ... -8.51834e+01  1.29985e+01
   1.29750e+03]] shape (8368, 60) type <class 'numpy.ndarray'>
nparray_output_all [[-1 -1 -1 ... -1  1  1]
 [ 1  1  1 ... -1 -1 -1]
 [ 1  1  1 ... -1 -1 -1]
 ...
 [ 1  1  1 ... -1 -1 -1]
 [-1  1  1 ... -1 -1 -1]
 [-1  1  1 ... -1 -1 -1]] shape (8368, 20) type <class 'numpy.ndarray'>
nparray_input_all [[-2.94873e+01 -1.24209e+01 -4.88990e+02 ... -7.38467e+01 -3.44037e+01
  -1.30200e+03]
 [-2.88767e+01 -1.41673e+01 -4.40389e+02 ... -8.25343e+01 -4.19861e+01
  -1.29750e

nparray_position [[ 5.30953e+01  5.92637e-01 -1.50250e+03]
 [ 4.90463e+01  5.43989e+00 -1.50250e+03]
 [ 7.27874e+01  7.75976e+00 -1.50250e+03]
 ...
 [-9.78331e+02  1.20597e+02  2.95550e+03]
 [-9.67621e+02  1.19253e+02  2.95250e+03]
 [-9.57845e+02  1.09019e+02  2.95250e+03]]
nparray_input_all [[-1.20874e+02  2.20973e+00 -1.49800e+03 ... -3.33855e+01 -1.27162e+00
  -4.24403e+02]
 [-3.40509e+01  6.31518e-01 -4.85018e+02 ... -5.98109e+01 -2.28935e+00
  -8.17500e+02]
 [-2.96028e+01 -1.20905e+01 -4.27966e+02 ... -6.30200e+01 -2.89135e+01
  -9.57500e+02]
 ...
 [-3.15788e+01 -1.58660e+00  4.37934e+02 ... -1.08938e+02 -1.06675e+01
   1.50200e+03]
 [-3.10748e+01  7.34919e+00  4.69576e+02 ... -5.26198e+01  1.45097e+01
   8.22000e+02]
 [-3.13367e+01  2.70658e+00  4.75255e+02 ... -6.06384e+01  6.55284e+00
   9.57500e+02]] shape (9132, 60) type <class 'numpy.ndarray'>
nparray_output_all [[ 1  1 -1 ... -1 -1 -1]
 [-1 -1 -1 ...  1  1  1]
 [ 1  1  1 ... -1 -1 -1]
 ...
 [ 1  1 -1 ... -1  1 -1]
 [ 1  1  

nparray_input_all [[  -29.3223    -12.8929   -420.716   ...   -48.6293    -23.4375
   -697.5    ]
 [  -29.8339    -11.4298   -458.76    ...   -80.2583    -30.0781
  -1302.     ]
 [  -30.3842     -9.85582  -427.555   ...   -57.462     -17.472
   -818.     ]
 ...
 [  -31.3338      2.7565    459.148   ...   -33.8083      1.43764
    473.349  ]
 [  -30.742      13.249     458.293   ...   -63.3813     30.9889
    958.     ]
 [  -31.1283      6.4007    419.798   ...   -42.4013      9.84542
    602.     ]] shape (8033, 60) type <class 'numpy.ndarray'>
nparray_output_all [[ 1  1  1 ... -1 -1 -1]
 [ 1  1 -1 ...  1 -1 -1]
 [ 1  1 -1 ...  1  1 -1]
 ...
 [-1 -1  1 ... -1 -1 -1]
 [ 1 -1  1 ... -1 -1 -1]
 [-1  1  1 ...  1  1 -1]] shape (8033, 20) type <class 'numpy.ndarray'>
nparray_input_all [[  -29.3223    -12.8929   -420.716   ...   -48.6293    -23.4375
   -697.5    ]
 [  -29.8339    -11.4298   -458.76    ...   -80.2583    -30.0781
  -1302.     ]
 [  -30.3842     -9.85582  -427.555   ...   -57.46

nparray_position [[ 3.00144e+01  2.78850e+00 -1.50250e+03]
 [ 5.12203e+01  5.05930e+00 -1.50250e+03]
 [ 5.78630e+01  1.67002e+00 -1.50250e+03]
 ...
 [-9.81331e+02  6.69705e+01  2.95250e+03]
 [-9.94288e+02  2.66645e+01  2.95250e+03]
 [-9.30281e+02  5.02428e+01  2.95250e+03]]
nparray_input_all [[-3.37256e+01 -2.98869e-01 -4.78074e+02 ... -6.06758e+01 -2.49325e+00
  -8.22500e+02]
 [-3.19739e+01 -5.30906e+00 -4.58735e+02 ... -6.44223e+01 -8.96170e+00
  -9.58000e+02]
 [-3.38493e+01  5.48360e-02 -4.21284e+02 ... -2.43619e+02  1.70741e+01
  -2.94850e+03]
 ...
 [-2.89199e+01  1.35489e+01  4.11216e+02 ... -5.59359e+01  2.67684e+01
   8.18000e+02]
 [-3.12075e+01  4.99640e+00  4.87934e+02 ... -6.15373e+01  5.16909e+00
   9.57500e+02]
 [-3.13423e+01  2.60673e+00  4.47260e+02 ... -6.15373e+01  5.16909e+00
   9.57500e+02]] shape (10074, 60) type <class 'numpy.ndarray'>
nparray_output_all [[-1 -1 -1 ...  1  1 -1]
 [-1  1  1 ...  1 -1 -1]
 [-1 -1 -1 ... -1 -1 -1]
 ...
 [ 1  1  1 ... -1 -1 -1]
 [-1 -1 

nparray_input_all [[ -31.8622    -5.62843 -486.041   ...  -43.8234   -10.1868  -698.     ]
 [ -29.3388   -12.8457  -435.175   ...  -68.7579   -29.9146  -962.     ]
 [ -32.3473    -4.24098 -454.851   ...  -49.8516    -8.11132 -702.5    ]
 ...
 [ -31.3423     2.60673  486.299   ...  -78.7904     7.47988 1297.5    ]
 [ -31.3254     2.90626  421.163   ...  -89.6093     8.3815  1297.5    ]
 [ -31.2225     4.73117  479.851   ...  -56.9734     8.66457  822.     ]] shape (8947, 60) type <class 'numpy.ndarray'>
nparray_output_all [[ 1  1  1 ... -1 -1 -1]
 [ 1  1  1 ... -1 -1 -1]
 [-1 -1 -1 ...  1  1  1]
 ...
 [ 1 -1  1 ...  1  1 -1]
 [-1 -1  1 ... -1 -1 -1]
 [ 1  1  1 ...  1 -1  1]] shape (8947, 20) type <class 'numpy.ndarray'>
nparray_input_all [[ -31.8622    -5.62843 -486.041   ...  -43.8234   -10.1868  -698.     ]
 [ -29.3388   -12.8457  -435.175   ...  -68.7579   -29.9146  -962.     ]
 [ -32.3473    -4.24098 -454.851   ...  -49.8516    -8.11132 -702.5    ]
 ...
 [ -31.3215     2.97517  455.

nparray_position [[   30.9515      5.21952 -1502.5    ]
 [   57.4711      4.498   -1502.5    ]
 [   37.6164      3.18617 -1502.5    ]
 ...
 [ -940.16       58.8493   2952.5    ]
 [ -973.732      22.1248   2952.5    ]
 [ -941.878      31.5432   2952.5    ]]
nparray_input_all [[-3.03784e+01 -9.87221e+00 -4.29363e+02 ... -2.99966e+01 -9.46421e+00
  -4.14224e+02]
 [-4.61508e+01 -6.47948e-01 -6.02500e+02 ... -5.40440e+01 -2.14136e+00
  -6.97500e+02]
 [-3.03726e+01 -9.88885e+00 -4.78926e+02 ... -3.02988e+01 -1.01001e+01
  -4.51381e+02]
 ...
 [-3.13451e+01  2.55681e+00  4.23860e+02 ... -5.07749e+01  2.11528e+00
   6.97500e+02]
 [-3.09348e+01  9.83008e+00  4.89268e+02 ... -6.44428e+01  1.82738e+01
   9.62000e+02]
 [-3.10897e+01  7.08418e+00  4.90343e+02 ... -7.13744e+01  1.25333e+01
   1.10200e+03]] shape (9590, 60) type <class 'numpy.ndarray'>
nparray_output_all [[-1  1  1 ... -1  1  1]
 [ 1 -1  1 ... -1 -1 -1]
 [ 1  1  1 ... -1 -1 -1]
 ...
 [-1  1  1 ... -1 -1 -1]
 [ 1  1  1 ... -1 -1 -1]
 [

nparray_input_all [[-3.39861e+01  4.46223e-01 -4.63918e+02 ... -3.19341e+01  9.07136e-01
  -4.68929e+02]
 [-3.15501e+01 -6.52113e+00 -4.50008e+02 ... -5.19170e+01 -1.06902e+01
  -6.98000e+02]
 [-3.41839e+01  1.01190e+00 -4.31675e+02 ... -8.32673e+01 -4.59493e-01
  -1.10250e+03]
 ...
 [-3.08683e+01  1.10101e+01  4.42480e+02 ... -3.95600e+01  1.73875e+01
   5.98000e+02]
 [-3.07018e+01  1.39603e+01  4.52501e+02 ... -5.43605e+01  3.02335e+01
   8.22500e+02]
 [-4.37921e+01 -1.64418e+00  5.97500e+02 ... -6.01594e+01 -2.76346e+00
   8.17500e+02]] shape (10210, 60) type <class 'numpy.ndarray'>
nparray_output_all [[-1 -1 -1 ...  1 -1 -1]
 [-1 -1 -1 ... -1 -1 -1]
 [-1 -1 -1 ...  1  1  1]
 ...
 [ 1  1  1 ...  1 -1 -1]
 [ 1  1  1 ... -1 -1 -1]
 [ 1  1  1 ... -1 -1 -1]] shape (10210, 20) type <class 'numpy.ndarray'>
nparray_input_all [[-3.39861e+01  4.46223e-01 -4.63918e+02 ... -3.19341e+01  9.07136e-01
  -4.68929e+02]
 [-3.15501e+01 -6.52113e+00 -4.50008e+02 ... -5.19170e+01 -1.06902e+01
  -6.9800

nparray_position [[ 6.15370e+01  1.53613e-01 -1.50250e+03]
 [ 8.03001e+01  9.80550e+00 -1.50250e+03]
 [ 3.50024e+01  3.93338e+00 -1.50250e+03]
 ...
 [-9.79929e+02  2.93682e+01  2.95250e+03]
 [-9.94069e+02  3.01376e+01  2.95250e+03]
 [-1.00431e+03  3.30661e+01  2.95250e+03]]
nparray_input_all [[-3.36681e+01 -4.63387e-01 -4.54622e+02 ... -5.19867e+01  1.05709e+00
  -6.97500e+02]
 [-7.04980e+01 -2.05691e+01 -1.10200e+03 ... -8.24975e+01 -2.10143e+01
  -1.29800e+03]
 [-3.05041e+01 -9.51294e+00 -4.58413e+02 ... -1.01950e+02 -3.16654e+01
  -1.49800e+03]
 ...
 [-2.85450e+01  1.31863e+01  4.34628e+02 ... -8.65610e+01  4.00490e+01
   1.29800e+03]
 [-3.12218e+01  4.74246e+00  4.85277e+02 ... -4.28718e+01  8.61524e+00
   6.97500e+02]
 [-3.12944e+01  3.45538e+00  4.25348e+02 ... -3.12103e+01  4.94717e+00
   4.26312e+02]] shape (10187, 60) type <class 'numpy.ndarray'>
nparray_output_all [[-1 -1  1 ... -1 -1 -1]
 [ 1  1  1 ... -1 -1 -1]
 [ 1  1 -1 ...  1  1  1]
 ...
 [ 1  1 -1 ...  1  1  1]
 [-1 -1 

nparray_input_all [[-3.11767e+01 -7.58905e+00 -4.82813e+02 ... -6.15519e+01 -1.77854e+01
  -9.58000e+02]
 [-3.43620e+01  1.52133e+00 -4.70691e+02 ... -4.33251e+01 -7.28000e-01
  -5.97500e+02]
 [-4.42653e+01 -1.07557e+01 -6.98000e+02 ... -6.15519e+01 -1.77854e+01
  -9.58000e+02]
 ...
 [-2.98473e+01  1.04837e+01  4.70779e+02 ... -3.68242e+01  1.38189e+01
   5.98000e+02]
 [-3.08154e+01  1.19467e+01  4.60160e+02 ... -5.52916e+01  1.88021e+01
   8.22000e+02]
 [-3.11169e+01  6.60203e+00  4.90155e+02 ... -5.90921e+01  1.11457e+01
   9.57500e+02]] shape (9915, 60) type <class 'numpy.ndarray'>
nparray_output_all [[-1 -1  1 ... -1 -1 -1]
 [ 1  1 -1 ... -1 -1 -1]
 [ 1  1 -1 ... -1 -1 -1]
 ...
 [-1 -1 -1 ...  1  1 -1]
 [-1 -1 -1 ... -1 -1 -1]
 [ 1  1  1 ... -1 -1 -1]] shape (9915, 20) type <class 'numpy.ndarray'>
nparray_input_all [[-3.11767e+01 -7.58905e+00 -4.82813e+02 ... -6.15519e+01 -1.77854e+01
  -9.58000e+02]
 [-3.43620e+01  1.52133e+00 -4.70691e+02 ... -4.33251e+01 -7.28000e-01
  -5.97500e

nparray_position [[   91.2479     11.2188  -1502.5    ]
 [   66.4139      9.16402 -1502.5    ]
 [   50.8465      9.0924  -1502.5    ]
 ...
 [ -993.316      42.1139   2952.5    ]
 [ -910.348      35.8119   2952.5    ]
 [-1017.3        -7.83869  2952.5    ]]
nparray_input_all [[  -32.5847     -3.56209  -442.136   ...   -50.0073     -6.68365
   -698.     ]
 [  -32.3164     -4.3293   -473.087   ...   -76.6666    -15.2436
  -1098.     ]
 [  -29.1243    -13.4593   -483.763   ...   -92.3288    -36.2144
  -1502.     ]
 ...
 [  -31.2156      4.85316   433.838   ...   -74.2916     11.5896
   1097.5    ]
 [  -29.7822     10.6189    429.418   ...   -78.7288     27.0092
   1098.     ]
 [  -30.7647     12.8458    447.472   ...   -48.7332     22.4319
    698.     ]] shape (9474, 60) type <class 'numpy.ndarray'>
nparray_output_all [[-1 -1 -1 ...  1 -1  1]
 [ 1 -1 -1 ... -1 -1 -1]
 [ 1  1  1 ... -1 -1 -1]
 ...
 [ 1 -1 -1 ...  1 -1  1]
 [-1 -1  1 ... -1 -1  1]
 [-1 -1 -1 ... -1  1  1]] shape (9474, 20) 

nparray_position [[ 9.54724e+01  3.42624e+00 -1.50250e+03]
 [ 4.54696e+01  2.85129e+00 -1.50250e+03]
 [ 5.26217e+01  1.60861e+00 -1.50250e+03]
 ...
 [-9.19333e+02  5.86211e+01  2.95250e+03]
 [-9.63888e+02  1.29686e+01  2.95250e+03]
 [-9.11832e+02  1.22185e+01  2.95250e+03]]
nparray_input_all [[  -31.2937     -7.25453  -438.146   ...   -75.8861    -17.1131
  -1098.     ]
 [  -29.0253    -13.7425   -428.769   ...   -39.0897    -18.4916
   -602.     ]
 [  -29.8857    -11.2816   -442.734   ...   -49.7912    -17.35
   -702.     ]
 ...
 [  -30.9306      9.90532   464.467   ...   -68.8723     27.5807
   1098.     ]
 [  -31.576      -1.53668   435.021   ...   -45.8223     -2.23672
    597.5    ]
 [  -32.6124     -1.9826    469.295   ...   -98.2769     -6.50577
   1502.5    ]] shape (8562, 60) type <class 'numpy.ndarray'>
nparray_output_all [[-1 -1 -1 ...  1  1 -1]
 [-1 -1  1 ... -1 -1 -1]
 [-1 -1  1 ... -1  1 -1]
 ...
 [-1  1  1 ... -1 -1 -1]
 [-1 -1  1 ... -1  1 -1]
 [-1 -1  1 ... -1 -1 -1]] 

nparray_position [[ 4.59201e+01  6.44772e+00 -1.50250e+03]
 [ 3.78619e+01  6.31507e+00 -1.50250e+03]
 [ 3.25736e+01  3.81871e-01 -1.50250e+03]
 ...
 [-1.00091e+03  8.70793e+01  2.95250e+03]
 [-9.12586e+02  2.42202e-01  2.95250e+03]
 [-9.31536e+02  3.02914e+01  2.95250e+03]]
nparray_input_all [[-3.22172e+01 -4.61313e+00 -4.44526e+02 ... -1.12410e+02 -1.39389e+01
  -1.49800e+03]
 [-3.24273e+01 -4.01235e+00 -4.76975e+02 ... -3.96775e+01 -8.42018e+00
  -5.98000e+02]
 [-3.14281e+01 -6.87012e+00 -4.66569e+02 ... -9.29426e+01 -2.02824e+01
  -1.29800e+03]
 ...
 [-3.07800e+01  1.25754e+01  4.54155e+02 ... -6.27898e+01  2.77132e+01
   9.58000e+02]
 [-3.15845e+01 -1.68644e+00  4.89214e+02 ... -3.99346e+01 -2.09824e+00
   5.97500e+02]
 [-3.14268e+01  1.10912e+00  4.61593e+02 ... -7.76301e+01  5.73346e+00
   1.09750e+03]] shape (10093, 60) type <class 'numpy.ndarray'>
nparray_output_all [[-1  1  1 ... -1  1 -1]
 [-1 -1  1 ... -1 -1 -1]
 [-1  1  1 ... -1 -1 -1]
 ...
 [-1 -1  1 ...  1 -1 -1]
 [-1  1 

nparray_input_all [[-4.12159e+01 -7.43167e+00 -6.02500e+02 ... -3.93493e+01 -8.34140e+00
  -5.98000e+02]
 [-3.14963e+01 -6.67505e+00 -4.83899e+02 ... -6.58616e+01 -1.18791e+01
  -9.62500e+02]
 [-4.06119e+01 -4.25173e+00 -5.97500e+02 ... -8.71880e+01 -1.19024e+01
  -1.30250e+03]
 ...
 [-3.15422e+01 -9.37631e-01  4.35090e+02 ... -6.87372e+01  2.82812e-01
   9.62500e+02]
 [-3.08137e+01  1.19766e+01  4.89346e+02 ... -6.57244e+01  2.76840e+01
   1.09800e+03]
 [-3.13676e+01  2.15745e+00  4.20547e+02 ... -8.68961e+01  4.85777e+00
   1.09750e+03]] shape (9287, 60) type <class 'numpy.ndarray'>
nparray_output_all [[ 1  1  1 ... -1 -1 -1]
 [-1 -1 -1 ...  1  1  1]
 [-1 -1 -1 ...  1  1  1]
 ...
 [-1 -1 -1 ...  1  1  1]
 [-1 -1 -1 ...  1 -1 -1]
 [-1 -1 -1 ...  1  1 -1]] shape (9287, 20) type <class 'numpy.ndarray'>
nparray_input_all [[-4.12159e+01 -7.43167e+00 -6.02500e+02 ... -3.93493e+01 -8.34140e+00
  -5.98000e+02]
 [-3.14963e+01 -6.67505e+00 -4.83899e+02 ... -6.58616e+01 -1.18791e+01
  -9.62500e

nparray_position [[ 5.01025e+01 -9.42955e-02 -1.50250e+03]
 [ 3.44703e+01  4.24258e+00 -1.50250e+03]
 [ 3.35061e+01  3.87152e-03 -1.50250e+03]
 ...
 [-8.68766e+02  1.02813e+02  2.95250e+03]
 [-9.64182e+02  8.29783e+00  2.95250e+03]
 [-9.20358e+02  4.23333e+01  2.95250e+03]]
nparray_input_all [[  -31.4511     -6.80432  -434.356   ...   -82.0547    -14.069
  -1098.     ]
 [  -65.7111     -2.82808  -957.5     ...   -38.268      -2.43002
   -597.5    ]
 [  -30.8675     -8.47345  -433.804   ...   -43.076      -8.72188
   -598.     ]
 ...
 [  -31.1126      6.67917   479.888   ...   -52.7307     10.2438
    817.5    ]
 [  -29.7171     10.754     423.404   ...   -30.046      11.212
    414.481  ]
 [  -31.1787      5.50642   468.062   ...   -84.2942     15.5837
   1302.     ]] shape (10682, 60) type <class 'numpy.ndarray'>
nparray_output_all [[-1 -1 -1 ... -1 -1 -1]
 [-1 -1 -1 ...  1 -1  1]
 [ 1  1  1 ... -1 -1 -1]
 ...
 [ 1  1  1 ... -1 -1 -1]
 [ 1  1  1 ... -1 -1 -1]
 [-1 -1 -1 ... -1 -1  1]]

nparray_position [[ 5.38176e+01  1.45196e+00 -1.50250e+03]
 [ 3.84780e+01  3.50475e+00 -1.50250e+03]
 [ 3.21873e+01  1.70564e+00 -1.50250e+03]
 ...
 [-8.98469e+02  5.89917e+01  2.95250e+03]
 [-8.94453e+02  1.22826e+02  2.95250e+03]
 [-9.36694e+02  1.13940e+02  2.95250e+03]]
nparray_input_all [[-8.32844e+01 -2.17174e+01 -1.29800e+03 ... -5.90755e+01 -1.36429e+01
  -9.58000e+02]
 [-3.22597e+01 -4.49160e+00 -4.36588e+02 ... -4.60323e+01 -7.20887e+00
  -6.02500e+02]
 [-3.26918e+01 -3.25579e+00 -4.24147e+02 ... -5.41248e+01 -7.51791e+00
  -6.98000e+02]
 ...
 [-3.26327e+01 -1.92463e+00  4.85107e+02 ... -5.70904e+01 -4.31757e+00
   8.22500e+02]
 [-3.30430e+01 -7.51030e-01  4.53925e+02 ... -4.41055e+01 -3.47523e+00
   5.97500e+02]
 [-3.25180e+01 -2.25280e+00  4.83236e+02 ... -6.72245e+01 -5.31576e+00
   9.62500e+02]] shape (8911, 60) type <class 'numpy.ndarray'>
nparray_output_all [[-1 -1 -1 ...  1 -1 -1]
 [-1  1  1 ... -1  1 -1]
 [ 1  1  1 ... -1 -1 -1]
 ...
 [-1 -1  1 ...  1 -1 -1]
 [ 1  1  

nparray_input_all [[-3.17949e+01 -5.82091e+00 -4.38495e+02 ... -4.94784e+01 -9.28196e+00
  -6.98000e+02]
 [-3.30485e+01 -2.23559e+00 -4.39912e+02 ... -9.90386e+01 -3.05458e-01
  -1.29750e+03]
 [-2.90913e+01 -1.35537e+01 -4.82790e+02 ... -8.21477e+01 -4.06564e+01
  -1.30200e+03]
 ...
 [-3.07442e+01  1.32104e+01  4.28944e+02 ... -9.81347e+01  3.70310e+01
   1.30200e+03]
 [-3.06817e+01  1.43173e+01  4.41012e+02 ... -7.09165e+01  3.30818e+01
   9.58000e+02]
 [-3.07938e+01  1.23295e+01  4.89714e+02 ... -4.82964e+01  2.25757e+01
   8.18000e+02]] shape (11552, 60) type <class 'numpy.ndarray'>
nparray_output_all [[-1 -1 -1 ... -1  1  1]
 [ 1  1  1 ... -1 -1 -1]
 [-1 -1 -1 ... -1  1 -1]
 ...
 [-1 -1 -1 ... -1 -1 -1]
 [ 1  1 -1 ... -1 -1  1]
 [-1 -1 -1 ... -1 -1 -1]] shape (11552, 20) type <class 'numpy.ndarray'>
nparray_input_all [[-3.17949e+01 -5.82091e+00 -4.38495e+02 ... -4.94784e+01 -9.28196e+00
  -6.98000e+02]
 [-3.30485e+01 -2.23559e+00 -4.39912e+02 ... -9.90386e+01 -3.05458e-01
  -1.2975

nparray_position [[ 7.08587e+01  1.43894e+00 -1.50250e+03]
 [ 3.65647e+01  4.15665e+00 -1.50250e+03]
 [ 4.02782e+01  7.15726e+00 -1.50250e+03]
 ...
 [-8.66652e+02  6.78114e+01  2.95250e+03]
 [-9.84466e+02  1.71490e+01  2.95250e+03]
 [-8.90094e+02  2.64817e+01  2.95250e+03]]
nparray_input_all [[-2.99989e+01 -1.09578e+01 -4.58475e+02 ... -7.18499e+01 -2.33234e+01
  -1.09800e+03]
 [-9.45991e+01  8.99937e-01 -1.29750e+03 ... -9.58591e+01 -5.41464e-02
  -1.29750e+03]
 [-5.64287e+01 -8.53381e+00 -8.18000e+02 ... -5.41053e+01 -8.02743e+00
  -8.18000e+02]
 ...
 [-3.31109e+01 -5.56843e-01  4.57986e+02 ... -9.19495e+01 -5.62463e-01
   1.29750e+03]
 [-3.12944e+01  3.45538e+00  4.61292e+02 ... -7.36764e+01  1.00867e+01
   1.09750e+03]
 [-3.32474e+01 -1.66398e-01  4.84338e+02 ... -4.92152e+01 -2.64437e-01
   6.97500e+02]] shape (9762, 60) type <class 'numpy.ndarray'>
nparray_output_all [[-1 -1 -1 ... -1 -1 -1]
 [ 1  1  1 ... -1 -1 -1]
 [-1 -1 -1 ...  1  1 -1]
 ...
 [ 1  1 -1 ... -1 -1 -1]
 [-1 -1 -

nparray_input_all [[-3.15006e+01 -6.66272e+00 -4.50298e+02 ... -7.00543e+01 -1.27306e+01
  -9.58000e+02]
 [-3.33049e+01 -1.50220e+00 -4.82024e+02 ... -5.98097e+01 -2.99161e+00
  -8.17500e+02]
 [-7.16722e+01 -1.77983e+01 -1.09800e+03 ... -8.65402e+01 -1.97223e+01
  -1.29800e+03]
 ...
 [-3.10204e+01  8.31308e+00  4.54621e+02 ... -4.24032e+01  1.09858e+01
   5.97500e+02]
 [-3.08389e+01  1.15304e+01  4.27606e+02 ... -7.37304e+01  2.58513e+01
   1.10200e+03]
 [-3.14296e+01  1.05919e+00  4.47185e+02 ... -1.10557e+02  3.68484e+00
   1.49800e+03]] shape (9396, 60) type <class 'numpy.ndarray'>
nparray_output_all [[ 1  1  1 ...  1 -1 -1]
 [ 1  1  1 ... -1 -1 -1]
 [ 1  1  1 ... -1 -1 -1]
 ...
 [-1 -1 -1 ...  1 -1 -1]
 [ 1  1  1 ... -1 -1 -1]
 [ 1  1 -1 ... -1 -1  1]] shape (9396, 20) type <class 'numpy.ndarray'>
nparray_input_all [[-3.15006e+01 -6.66272e+00 -4.50298e+02 ... -7.00543e+01 -1.27306e+01
  -9.58000e+02]
 [-3.33049e+01 -1.50220e+00 -4.82024e+02 ... -5.98097e+01 -2.99161e+00
  -8.17500e

nparray_position [[ 3.92924e+01  6.77874e+00 -1.50250e+03]
 [ 8.37134e+01  8.01779e+00 -1.50250e+03]
 [ 6.23576e+01  1.00987e+01 -1.50250e+03]
 ...
 [-8.74072e+02 -2.30109e+00  2.95250e+03]
 [-9.08826e+02  6.00040e+01  2.95250e+03]
 [-8.89220e+02  4.03742e+01  2.95250e+03]]
nparray_input_all [[-3.27839e+01 -2.99231e+00 -4.36060e+02 ... -8.13627e+01 -1.54612e+00
  -1.09750e+03]
 [-2.98999e+01 -1.12410e+01 -4.55920e+02 ... -3.03465e+01 -9.96363e+00
  -4.49461e+02]
 [-3.41976e+01  1.05120e+00 -4.42061e+02 ... -1.11010e+02  1.20310e+00
  -1.49800e+03]
 ...
 [-3.15929e+01 -1.83620e+00  4.40078e+02 ... -6.08433e+01  3.52373e-01
   8.22500e+02]
 [-3.11819e+01  5.44967e+00  4.61067e+02 ... -5.68353e+01  1.14081e+01
   8.22000e+02]
 [-3.10286e+01  8.16763e+00  4.19998e+02 ... -3.09683e+01  9.23626e+00
   4.56109e+02]] shape (9622, 60) type <class 'numpy.ndarray'>
nparray_output_all [[-1  1  1 ... -1 -1 -1]
 [ 1  1 -1 ... -1 -1 -1]
 [-1 -1  1 ... -1 -1  1]
 ...
 [-1 -1 -1 ...  1 -1 -1]
 [ 1  1  

nparray_input_all [[-3.19668e+01 -5.32933e+00 -4.68884e+02 ... -7.35077e+01 -1.22300e+01
  -1.10250e+03]
 [-3.39063e+01  2.17944e-01 -4.59546e+02 ... -9.84488e+01 -1.45369e+00
  -1.30250e+03]
 [-3.21931e+01 -4.68200e+00 -4.55562e+02 ... -9.21331e+01 -1.64253e+01
  -1.29800e+03]
 ...
 [-3.15676e+01 -1.38692e+00  4.86400e+02 ... -9.01156e+01 -6.96686e+00
   1.30250e+03]
 [-3.10370e+01  8.01890e+00  4.24117e+02 ... -3.15323e+01  8.02997e+00
   4.04613e+02]
 [-3.06981e+01  1.40266e+01  4.64099e+02 ... -5.55021e+01  2.57228e+01
   8.18000e+02]] shape (9916, 60) type <class 'numpy.ndarray'>
nparray_output_all [[ 1 -1 -1 ...  1 -1  1]
 [ 1  1 -1 ...  1 -1 -1]
 [-1  1  1 ... -1  1 -1]
 ...
 [-1  1  1 ... -1 -1 -1]
 [ 1 -1 -1 ... -1 -1 -1]
 [ 1  1  1 ... -1 -1 -1]] shape (9916, 20) type <class 'numpy.ndarray'>
nparray_input_all [[-3.19668e+01 -5.32933e+00 -4.68884e+02 ... -7.35077e+01 -1.22300e+01
  -1.10250e+03]
 [-3.39063e+01  2.17944e-01 -4.59546e+02 ... -9.84488e+01 -1.45369e+00
  -1.30250e

nparray_position [[ 8.84164e+01  6.33159e+00 -1.50250e+03]
 [ 8.29015e+01  1.11638e+01 -1.50250e+03]
 [ 3.09301e+01  1.90762e+00 -1.50250e+03]
 ...
 [-9.37026e+02  1.08671e+02  2.95250e+03]
 [-9.77519e+02  1.27571e+02  2.95250e+03]
 [-9.72926e+02  3.49395e+01  2.95250e+03]]
nparray_input_all [[-2.95863e+01 -1.21377e+01 -4.39828e+02 ... -3.76260e+01 -1.92162e+01
  -5.97500e+02]
 [-3.14410e+01 -6.83309e+00 -4.75793e+02 ... -8.16088e+01 -1.76129e+01
  -1.29800e+03]
 [-3.26193e+01 -3.46318e+00 -4.85676e+02 ... -5.31516e+01 -5.61253e+00
  -8.22500e+02]
 ...
 [-2.88272e+01  1.26008e+01  4.25891e+02 ... -2.96520e+01  1.08891e+01
   4.22364e+02]
 [-3.15169e+01 -4.88346e-01  4.59264e+02 ... -5.53954e+01 -3.53964e+00
   8.17500e+02]
 [-3.14465e+01  7.59670e-01  4.46630e+02 ... -6.02966e+01 -8.58467e-01
   8.22500e+02]] shape (8062, 60) type <class 'numpy.ndarray'>
nparray_output_all [[ 1  1 -1 ... -1 -1 -1]
 [-1 -1 -1 ... -1  1 -1]
 [-1  1 -1 ... -1 -1 -1]
 ...
 [ 1  1  1 ... -1 -1 -1]
 [-1 -1 -

nparray_input_all [[-3.38646e+01  9.87360e-02 -4.53971e+02 ... -4.36728e+01  1.30555e+00
  -5.97500e+02]
 [-2.93913e+01 -1.26955e+01 -4.43640e+02 ... -4.20593e+01 -1.74486e+01
  -6.02000e+02]
 [-2.93058e+01 -1.29401e+01 -4.36173e+02 ... -4.85599e+01 -2.14598e+01
  -6.97500e+02]
 ...
 [-3.14411e+01  8.55714e-01  4.84116e+02 ... -6.08002e+01 -1.95932e-01
   9.62500e+02]
 [-2.92212e+01  1.29236e+01  4.03161e+02 ... -4.18958e+01  1.86256e+01
   5.98000e+02]
 [-3.10214e+01  8.29598e+00  4.77264e+02 ... -5.50428e+01  1.09774e+01
   8.17500e+02]] shape (9011, 60) type <class 'numpy.ndarray'>
nparray_output_all [[ 1  1  1 ... -1 -1 -1]
 [ 1  1 -1 ... -1 -1 -1]
 [-1 -1 -1 ...  1 -1 -1]
 ...
 [ 1  1  1 ... -1 -1 -1]
 [-1 -1 -1 ... -1  1 -1]
 [-1  1  1 ... -1 -1 -1]] shape (9011, 20) type <class 'numpy.ndarray'>
nparray_input_all [[-3.38646e+01  9.87360e-02 -4.53971e+02 ... -4.36728e+01  1.30555e+00
  -5.97500e+02]
 [-2.93913e+01 -1.26955e+01 -4.43640e+02 ... -4.20593e+01 -1.74486e+01
  -6.02000e

In [25]:
# combine all numpy arrays into one
eventNumber="all"
fileNameNNInputTrainAll=outputFolderName+"/NN_2_data_Input_Train_"+eventNumber+".npy"
fileNameNNOutputTrainAll=outputFolderName+"/NN_2_data_Output_Train_"+eventNumber+".npy"
fileNameNNInputTestAll=outputFolderName+"/NN_2_data_Input_Test_"+eventNumber+".npy"
fileNameNNOutputTestAll=outputFolderName+"/NN_2_data_Output_Test_"+eventNumber+".npy"
    
for i,eventNumber in enumerate(list_eventNumber):
    fileNameNNInputTrain=outputFolderName+"/NN_2_data_Input_Train_"+eventNumber+".npy"
    fileNameNNOutputTrain=outputFolderName+"/NN_2_data_Output_Train_"+eventNumber+".npy"
    fileNameNNInputTest=outputFolderName+"/NN_2_data_Input_Test_"+eventNumber+".npy"
    fileNameNNOutputTest=outputFolderName+"/NN_2_data_Output_Test_"+eventNumber+".npy"
    
    nparray_Input_Train=np.load(fileNameNNInputTrain)
    nparray_Input_Test=np.load(fileNameNNInputTest)
    nparray_Output_Train=np.load(fileNameNNOutputTrain)
    nparray_Output_Test=np.load(fileNameNNOutputTest)
    
    if i==0:
        nparray_Input_Train_all=nparray_Input_Train
        nparray_Input_Test_all=nparray_Input_Test
        nparray_Output_Train_all=nparray_Output_Train
        nparray_Output_Test_all=nparray_Output_Test
    else:
        nparray_Input_Train_all=np.concatenate((nparray_Input_Train_all,nparray_Input_Train),axis=0,out=None)
        nparray_Input_Test_all=np.concatenate((nparray_Input_Test_all,nparray_Input_Test),axis=0,out=None)
        nparray_Output_Train_all=np.concatenate((nparray_Output_Train_all,nparray_Output_Train),axis=0,out=None)
        nparray_Output_Test_all=np.concatenate((nparray_Output_Test_all,nparray_Output_Test),axis=0,out=None)
    # done if
# done for loop 

print("nparray_Input_Train_all",nparray_Input_Train_all,"shape",nparray_Input_Train_all.shape,"type",type(nparray_Input_Train_all))
print("nparray_Input_Test_all",nparray_Input_Test_all,"shape",nparray_Input_Test_all.shape,"type",type(nparray_Input_Test_all))
print("nparray_Output_Train_all",nparray_Output_Train_all,"shape",nparray_Output_Train_all.shape,"type",type(nparray_Output_Train_all))
print("nparray_Output_Test_all",nparray_Output_Test_all,"shape",nparray_Output_Test_all.shape,"type",type(nparray_Output_Test_all))

np.save(fileNameNNInputTrainAll,nparray_Input_Train_all)
np.save(fileNameNNInputTestAll,nparray_Input_Test_all)
np.save(fileNameNNOutputTrainAll,nparray_Output_Train_all)
np.save(fileNameNNOutputTestAll,nparray_Output_Test_all)

nparray_Input_Train_all [[[-3.23306e+01]
  [-4.28872e+00]
  [-4.62092e+02]
  ...
  [-8.93000e+01]
  [-1.51782e+01]
  [-1.30250e+03]]

 [[-3.04775e+01]
  [-9.58902e+00]
  [-4.21256e+02]
  ...
  [-1.12212e+02]
  [-4.01146e+01]
  [-1.49800e+03]]

 [[-3.19316e+01]
  [-5.42998e+00]
  [-4.84890e+02]
  ...
  [-8.34928e+01]
  [-1.48256e+01]
  [-1.29800e+03]]

 ...

 [[-3.13739e+01]
  [ 2.04705e+00]
  [ 4.87235e+02]
  ...
  [-6.26886e+01]
  [ 6.31295e+00]
  [ 9.57500e+02]]

 [[-3.09550e+01]
  [ 9.47315e+00]
  [ 4.64051e+02]
  ...
  [-4.04887e+01]
  [ 1.09354e+01]
  [ 5.97500e+02]]

 [[-3.31662e+01]
  [-3.98620e-01]
  [ 4.46810e+02]
  ...
  [-7.94153e+01]
  [ 2.56644e-01]
  [ 1.09750e+03]]] shape (478540, 60, 1) type <class 'numpy.ndarray'>
nparray_Input_Test_all [[[  -30.0484 ]
  [  -10.8162 ]
  [ -427.981  ]
  ...
  [  -47.7968 ]
  [  -14.5214 ]
  [ -702.     ]]

 [[  -31.7544 ]
  [   -5.93686]
  [ -455.191  ]
  ...
  [ -102.996  ]
  [  -17.4721 ]
  [-1498.     ]]

 [[  -29.4708 ]
  [  -12.468

In [2]:
import numpy as np
l1=[1,2,3]
l2=[7,8,9]
l3=[5,4,6]


In [4]:
nparray_l1=np.array(l1)
nparray_l1

array([1, 2, 3])

In [5]:
nparray_l2=np.array(l2)
nparray_l2

array([7, 8, 9])

In [6]:
nparray_l3=np.array(l3)
nparray_l3

array([5, 4, 6])

In [13]:
n=np.concatenate((l1,l2,l3),axis=0,out=None)
n

array([1, 2, 3, 7, 8, 9, 5, 4, 6])

In [10]:
list_nparray=[nparray_l1,nparray_l2,nparray_l3]
list_nparray

[array([1, 2, 3]), array([7, 8, 9]), array([5, 4, 6])]

In [18]:
for i,nparray in enumerate(list_nparray):
    if i==0:
        nparray_all=nparray
    else:
        nparray_all=np.concatenate((nparray_all,nparray),axis=0,out=None)
print(nparray_all.shape,nparray_all.dtype,type(nparray_all))

(9,) int64 <class 'numpy.ndarray'>
